---
- name: Install unzip
  apt: pkg=unzip state=present

- name: Downloading packer binary from official repo .
  get_url: url={{ packer_binary_link }} dest=/tmp/packer.zip mode=0777

- name: extract to /usr/local/bin/.
  command: unzip /tmp/packer.zip -d /usr/local/bin/
  async: 1

- name: permission for packer.
  file: path=/usr/local/bin/packer mode=0655

